name=cpp_bus_driver
version=2.2.0
author=Llgok
maintainer=Llgok
sentence=A C++11 peripheral bus and chip driver library.
paragraph=Provides unified bus and chip drivers for supported embedded frameworks.
category=Device Control
url=https://github.com/Llgok/cpp_bus_driver
architectures=nrf52
includes=cpp_bus_driver_library.h
