name=cpp_bus_driver
version=2.3.0
author=Llgok
maintainer=Llgok
sentence=A C++11 peripheral bus and chip driver library.
paragraph=Provides unified bus and chip drivers compatible with ESP-IDF and Arduino platforms.
category=Device Control
url=https://github.com/Llgok/cpp_bus_driver
architectures=nrf52,esp32
includes=cpp_bus_driver.h
